<?php
// Auto-generated by data warp compiler from generated/plantkeeper_database.datawarp
// flowcpp datawarp_compiler.flow -- file=generated/plantkeeper_database.datawarp flowfile=generated/plantkeeper_database.flow baseurl=/php/ phppage=plantkeeper_database.php wwwfolder=www/php/ requestfn=oauthDatawarpRequest 
include 'datawarputil.php';
include '../oauth/utils/security.php'; 


function deleteCarePlan(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM care_plans
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function deleteColorType(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM color_types
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function deleteFamily(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM families
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function deleteLeafType(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM leaf_types
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function deletePlant(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM plants
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function deletePlantColor(/* $(val.id) */ $a0) {
	$result = array();
	$sql = "DELETE FROM plant_colors
	WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function insertCarePlan(/* $(val.name) */ $a0, /* $(val.description) */ $a1, /* $(val.pour) */ $a2, /* $(val.light |> b2i) */ $a3, /* $(val.turn) */ $a4, /* $(val.tempreture) */ $a5, /* $(val.spray) */ $a6, /* $(val.wipeLeaves) */ $a7) {
	$result = array();
	$sql = "INSERT INTO care_plans (`name`, `description`, `pour`, `light`, `turn`, `tempreture`, `spray`, `wipe_leaves`)
	VALUES (:a0 , :a1 , :a2 , :a3 , :a4 , :a5 , :a6 , :a7 )";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2, 'a3' => $a3, 'a4' => $a4, 'a5' => $a5, 'a6' => $a6, 'a7' => $a7));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function insertColorType(/* $(val.name) */ $a0) {
	$result = array();
	$sql = "INSERT INTO color_types (`name`)
	VALUES (:a0 )";
	$result[] = exec_query("", $sql, array('a0' => $a0));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function insertFamily(/* $(val.name) */ $a0, /* $(val.description) */ $a1) {
	$result = array();
	$sql = "INSERT INTO families (`name`, `description`)
	VALUES (:a0 , :a1 )";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function insertLeafType(/* $(val.name) */ $a0, /* $(val.description) */ $a1) {
	$result = array();
	$sql = "INSERT INTO leaf_types (`name`, `description`)
	VALUES (:a0 , :a1 )";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function insertPlant(/* $(val.name) */ $a0, /* $(val.familyId) */ $a1, /* $(val.leafColorId) */ $a2, /* $(val.budColorId) */ $a3, /* $(val.height) */ $a4, /* $(val.leafTypeId) */ $a5, /* $(val.carePlanId) */ $a6) {
	$result = array();
	$sql = "INSERT INTO plants (`name`, `family_id`, `leaf_color_id`, `bud_color_id`, `height`, `leaf_type_id`, `care_plan_id`)
	VALUES (:a0 , :a1 , :a2 , :a3 , :a4 , :a5 , :a6 )";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2, 'a3' => $a3, 'a4' => $a4, 'a5' => $a5, 'a6' => $a6));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function insertPlantColor(/* $(val.name) */ $a0, /* $(val.colorNumber) */ $a1, /* $(val.colorTypeId) */ $a2) {
	$result = array();
	$sql = "INSERT INTO plant_colors (`name`, `color_number`, `color_type_id`)
	VALUES (:a0 , :a1 , :a2 )";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2));
	$sql = "SELECT LAST_INSERT_ID() AS id";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadCarePlan(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT care_plans.`id` AS `id`, care_plans.`name` AS `name`, care_plans.`description` AS `description`, care_plans.`pour` AS `pour`, care_plans.`light` AS `light`, care_plans.`turn` AS `turn`, care_plans.`tempreture` AS `tempreture`, care_plans.`spray` AS `spray`, care_plans.`wipe_leaves` AS `wipeLeaves` FROM care_plans
	WHERE care_plans.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadCarePlans() {
	$result = array();
	$sql = "SELECT care_plans.`id` AS `care_plans_id`, care_plans.`name` AS `care_plans_name`, care_plans.`description` AS `care_plans_description`, care_plans.`pour` AS `care_plans_pour`, care_plans.`light` AS `care_plans_light`, care_plans.`turn` AS `care_plans_turn`, care_plans.`tempreture` AS `care_plans_tempreture`, care_plans.`spray` AS `care_plans_spray`, care_plans.`wipe_leaves` AS `care_plans_wipeLeaves`
	FROM care_plans";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadColorType(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT color_types.`id` AS `id`, color_types.`name` AS `name` FROM color_types
	WHERE color_types.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadColorTypes() {
	$result = array();
	$sql = "SELECT color_types.`id` AS `color_types_id`, color_types.`name` AS `color_types_name`
	FROM color_types";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadFamily(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT families.`id` AS `id`, families.`name` AS `name`, families.`description` AS `description` FROM families
	WHERE families.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadFamilys() {
	$result = array();
	$sql = "SELECT families.`id` AS `families_id`, families.`name` AS `families_name`, families.`description` AS `families_description`
	FROM families";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadLeafType(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT leaf_types.`id` AS `id`, leaf_types.`name` AS `name`, leaf_types.`description` AS `description` FROM leaf_types
	WHERE leaf_types.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadLeafTypes() {
	$result = array();
	$sql = "SELECT leaf_types.`id` AS `leaf_types_id`, leaf_types.`name` AS `leaf_types_name`, leaf_types.`description` AS `leaf_types_description`
	FROM leaf_types";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadPlant(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `id`, plants.`name` AS `name`, plants.`family_id` AS `familyId`, plants.`leaf_color_id` AS `leafColorId`, plants.`bud_color_id` AS `budColorId`, plants.`height` AS `height`, plants.`leaf_type_id` AS `leafTypeId`, plants.`care_plan_id` AS `carePlanId` FROM plants
	WHERE plants.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantColor(/* $(id) */ $a0) {
	$result = array();
	$sql = "SELECT plant_colors.`id` AS `id`, plant_colors.`name` AS `name`, plant_colors.`color_number` AS `colorNumber`, plant_colors.`color_type_id` AS `colorTypeId` FROM plant_colors
	WHERE plant_colors.`id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantColors() {
	$result = array();
	$sql = "SELECT plant_colors.`id` AS `plant_colors_id`, plant_colors.`name` AS `plant_colors_name`, plant_colors.`color_number` AS `plant_colors_colorNumber`, plant_colors.`color_type_id` AS `plant_colors_colorTypeId`
	FROM plant_colors";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadPlantColorsByColorTypeId(/* $(colorTypeId) */ $a0) {
	$result = array();
	$sql = "SELECT plant_colors.`id` AS `plant_colors_id`, plant_colors.`name` AS `plant_colors_name`, plant_colors.`color_number` AS `plant_colors_colorNumber`, plant_colors.`color_type_id` AS `plant_colors_colorTypeId` FROM plant_colors
	WHERE plant_colors.`color_type_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlants() {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId`
	FROM plants";
	$result[] = exec_query("", $sql, array());

	return $result;
}


function loadPlantsByBudColorId(/* $(plantColorId) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId` FROM plants
	WHERE plants.`bud_color_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantsByCarePlanId(/* $(carePlanId) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId` FROM plants
	WHERE plants.`care_plan_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantsByFamilyId(/* $(familieId) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId` FROM plants
	WHERE plants.`family_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantsByLeafColorId(/* $(plantColorId) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId` FROM plants
	WHERE plants.`leaf_color_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function loadPlantsByLeafTypeId(/* $(leafTypeId) */ $a0) {
	$result = array();
	$sql = "SELECT plants.`id` AS `plants_id`, plants.`name` AS `plants_name`, plants.`family_id` AS `plants_familyId`, plants.`leaf_color_id` AS `plants_leafColorId`, plants.`bud_color_id` AS `plants_budColorId`, plants.`height` AS `plants_height`, plants.`leaf_type_id` AS `plants_leafTypeId`, plants.`care_plan_id` AS `plants_carePlanId` FROM plants
	WHERE plants.`leaf_type_id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0));

	return $result;
}


function updateCarePlan(/* $(val.id) */ $a0, /* $(val.name) */ $a1, /* $(val.description) */ $a2, /* $(val.pour) */ $a3, /* $(val.light |> b2i) */ $a4, /* $(val.turn) */ $a5, /* $(val.tempreture) */ $a6, /* $(val.spray) */ $a7, /* $(val.wipeLeaves) */ $a8) {
	$result = array();
	$sql = "UPDATE care_plans SET `name` = :a1 , `description` = :a2 , `pour` = :a3 , `light` = :a4 , `turn` = :a5 , `tempreture` = :a6 , `spray` = :a7 , `wipe_leaves` = :a8 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2, 'a3' => $a3, 'a4' => $a4, 'a5' => $a5, 'a6' => $a6, 'a7' => $a7, 'a8' => $a8));

	return $result;
}


function updateColorType(/* $(val.id) */ $a0, /* $(val.name) */ $a1) {
	$result = array();
	$sql = "UPDATE color_types SET `name` = :a1 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1));

	return $result;
}


function updateFamily(/* $(val.id) */ $a0, /* $(val.name) */ $a1, /* $(val.description) */ $a2) {
	$result = array();
	$sql = "UPDATE families SET `name` = :a1 , `description` = :a2 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2));

	return $result;
}


function updateLeafType(/* $(val.id) */ $a0, /* $(val.name) */ $a1, /* $(val.description) */ $a2) {
	$result = array();
	$sql = "UPDATE leaf_types SET `name` = :a1 , `description` = :a2 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2));

	return $result;
}


function updatePlant(/* $(val.id) */ $a0, /* $(val.name) */ $a1, /* $(val.familyId) */ $a2, /* $(val.leafColorId) */ $a3, /* $(val.budColorId) */ $a4, /* $(val.height) */ $a5, /* $(val.leafTypeId) */ $a6, /* $(val.carePlanId) */ $a7) {
	$result = array();
	$sql = "UPDATE plants SET `name` = :a1 , `family_id` = :a2 , `leaf_color_id` = :a3 , `bud_color_id` = :a4 , `height` = :a5 , `leaf_type_id` = :a6 , `care_plan_id` = :a7 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2, 'a3' => $a3, 'a4' => $a4, 'a5' => $a5, 'a6' => $a6, 'a7' => $a7));

	return $result;
}


function updatePlantColor(/* $(val.id) */ $a0, /* $(val.name) */ $a1, /* $(val.colorNumber) */ $a2, /* $(val.colorTypeId) */ $a3) {
	$result = array();
	$sql = "UPDATE plant_colors SET `name` = :a1 , `color_number` = :a2 , `color_type_id` = :a3 WHERE `id` = :a0";
	$result[] = exec_query("", $sql, array('a0' => $a0, 'a1' => $a1, 'a2' => $a2, 'a3' => $a3));

	return $result;
}

authenticate();

switch (getParameter("operation")) {
	case "deleteCarePlan":
		$a0 = getParameter("a0");
		$res = deleteCarePlan($a0);
		printOkAndJson($res);
		break;
	case "deleteColorType":
		$a0 = getParameter("a0");
		$res = deleteColorType($a0);
		printOkAndJson($res);
		break;
	case "deleteFamily":
		$a0 = getParameter("a0");
		$res = deleteFamily($a0);
		printOkAndJson($res);
		break;
	case "deleteLeafType":
		$a0 = getParameter("a0");
		$res = deleteLeafType($a0);
		printOkAndJson($res);
		break;
	case "deletePlant":
		$a0 = getParameter("a0");
		$res = deletePlant($a0);
		printOkAndJson($res);
		break;
	case "deletePlantColor":
		$a0 = getParameter("a0");
		$res = deletePlantColor($a0);
		printOkAndJson($res);
		break;
	case "insertCarePlan":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$a3 = getParameter("a3");
		$a4 = getParameter("a4");
		$a5 = getParameter("a5");
		$a6 = getParameter("a6");
		$a7 = getParameter("a7");
		$res = insertCarePlan($a0, $a1, $a2, $a3, $a4, $a5, $a6, $a7);
		printOkAndJson($res);
		break;
	case "insertColorType":
		$a0 = getParameter("a0");
		$res = insertColorType($a0);
		printOkAndJson($res);
		break;
	case "insertFamily":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$res = insertFamily($a0, $a1);
		printOkAndJson($res);
		break;
	case "insertLeafType":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$res = insertLeafType($a0, $a1);
		printOkAndJson($res);
		break;
	case "insertPlant":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$a3 = getParameter("a3");
		$a4 = getParameter("a4");
		$a5 = getParameter("a5");
		$a6 = getParameter("a6");
		$res = insertPlant($a0, $a1, $a2, $a3, $a4, $a5, $a6);
		printOkAndJson($res);
		break;
	case "insertPlantColor":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$res = insertPlantColor($a0, $a1, $a2);
		printOkAndJson($res);
		break;
	case "loadCarePlan":
		$a0 = getParameter("a0");
		$res = loadCarePlan($a0);
		printOkAndJson($res);
		break;
	case "loadCarePlans":
		$res = loadCarePlans();
		printOkAndJson($res);
		break;
	case "loadColorType":
		$a0 = getParameter("a0");
		$res = loadColorType($a0);
		printOkAndJson($res);
		break;
	case "loadColorTypes":
		$res = loadColorTypes();
		printOkAndJson($res);
		break;
	case "loadFamily":
		$a0 = getParameter("a0");
		$res = loadFamily($a0);
		printOkAndJson($res);
		break;
	case "loadFamilys":
		$res = loadFamilys();
		printOkAndJson($res);
		break;
	case "loadLeafType":
		$a0 = getParameter("a0");
		$res = loadLeafType($a0);
		printOkAndJson($res);
		break;
	case "loadLeafTypes":
		$res = loadLeafTypes();
		printOkAndJson($res);
		break;
	case "loadPlant":
		$a0 = getParameter("a0");
		$res = loadPlant($a0);
		printOkAndJson($res);
		break;
	case "loadPlantColor":
		$a0 = getParameter("a0");
		$res = loadPlantColor($a0);
		printOkAndJson($res);
		break;
	case "loadPlantColors":
		$res = loadPlantColors();
		printOkAndJson($res);
		break;
	case "loadPlantColorsByColorTypeId":
		$a0 = getParameter("a0");
		$res = loadPlantColorsByColorTypeId($a0);
		printOkAndJson($res);
		break;
	case "loadPlants":
		$res = loadPlants();
		printOkAndJson($res);
		break;
	case "loadPlantsByBudColorId":
		$a0 = getParameter("a0");
		$res = loadPlantsByBudColorId($a0);
		printOkAndJson($res);
		break;
	case "loadPlantsByCarePlanId":
		$a0 = getParameter("a0");
		$res = loadPlantsByCarePlanId($a0);
		printOkAndJson($res);
		break;
	case "loadPlantsByFamilyId":
		$a0 = getParameter("a0");
		$res = loadPlantsByFamilyId($a0);
		printOkAndJson($res);
		break;
	case "loadPlantsByLeafColorId":
		$a0 = getParameter("a0");
		$res = loadPlantsByLeafColorId($a0);
		printOkAndJson($res);
		break;
	case "loadPlantsByLeafTypeId":
		$a0 = getParameter("a0");
		$res = loadPlantsByLeafTypeId($a0);
		printOkAndJson($res);
		break;
	case "updateCarePlan":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$a3 = getParameter("a3");
		$a4 = getParameter("a4");
		$a5 = getParameter("a5");
		$a6 = getParameter("a6");
		$a7 = getParameter("a7");
		$a8 = getParameter("a8");
		$res = updateCarePlan($a0, $a1, $a2, $a3, $a4, $a5, $a6, $a7, $a8);
		printOkAndJson($res);
		break;
	case "updateColorType":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$res = updateColorType($a0, $a1);
		printOkAndJson($res);
		break;
	case "updateFamily":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$res = updateFamily($a0, $a1, $a2);
		printOkAndJson($res);
		break;
	case "updateLeafType":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$res = updateLeafType($a0, $a1, $a2);
		printOkAndJson($res);
		break;
	case "updatePlant":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$a3 = getParameter("a3");
		$a4 = getParameter("a4");
		$a5 = getParameter("a5");
		$a6 = getParameter("a6");
		$a7 = getParameter("a7");
		$res = updatePlant($a0, $a1, $a2, $a3, $a4, $a5, $a6, $a7);
		printOkAndJson($res);
		break;
	case "updatePlantColor":
		$a0 = getParameter("a0");
		$a1 = getParameter("a1");
		$a2 = getParameter("a2");
		$a3 = getParameter("a3");
		$res = updatePlantColor($a0, $a1, $a2, $a3);
		printOkAndJson($res);
		break;

	default: 
		logRequestError("Unknown operation: " . getParameter("operation"));
		echo("Unknown operation: " . getParameter("operation"));
		break;
}
?>